name: islamibilgiler
description: "Namaz Sure ve Duaları"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Paket sürümlerini uyumlu hale getiriyoruz
  geolocator: ^13.0.4 # <- Sürümü 12.0.0'dan 10.1.0'a düşürüyoruz
  geocoding: ^2.1.1 # BU SATIRI EKLEYİN
  flutter_qiblah: ^3.1.0+1

  adhan: ^2.0.0-nullsafety.1
  intl: ^0.20.2
  flutter_timezone: ^4.1.1
  flutter_local_notifications: ^19.4.0
  timezone: ^0.10.1

  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  html: ^0.15.4

  cupertino_icons: ^1.0.2
  google_mobile_ads: ^6.0.0
  url_launcher: ^6.2.6
  change_app_package_name: ^1.5.0
  flutter_widget_from_html_core: ^0.10.2 # BU SATIRI EKLEYİN
  timer_builder: ^2.0.0 # BU SATIRI EKLEYİN
  vibration: ^3.1.3 # BU SATIRI
  flutter_launcher_icons: ^0.14.4



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/data/ # BU SATIRI EKLEYİN
    - assets/sesler/ # Ezan sesi için
    - assets/images/

flutter_launcher_icons:
  android: true
  image_path: "assets/images/logo.jpg"
  min_sdk_android: 23 # Projenizin minimum SDK versiyonu